controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
user_register:
    path: /register
    controller: App\Controller\UserController::register
user_login:
    path: /login
    controller: App\Controller\UserController::login
user_logout:
    path: /logout
    controller: App\Controller\UserController::logout